[package]
name = "port_scanner"
version = "0.1.0"
edition = "2021"
authors = ["Thultanthar"]
description = "Asynchronous Port Scanner"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
clap = "3.0"
