[package]
name = "adv-network-scan"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ipnetwork = "0.18.0"
rand = "0.8"
ping = "0.4.1"
pnet= "0.30.0"
clap = "3.2.1"

